log:
  development: true
  type: 1
  logFilePath: "./log/worker.log"
  autoCreateFile: true

db:
  host: localhost
  port: 3306
  username: oj
  password: "123456"
  dbName: online_judge
  tablePrefix: ""
  maxOpenConns: 10
  maxIdleConns: 10
  connMaxLifetime: 30
  connMaxIdleTime: 30

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""

kafka:
  brokers:
    - localhost:9092

judgerWorker:
  containerPoolSize: 2
  compileTimeoutSeconds: 60
  defaultMemoryLimitMB: 256
  xAutoClaimTimeoutMinutes: 5
  testcasePathPrefix: "/testcases"
